general:
  setupCommonPipelineEnvironment:
     collectTelemetryData: false
     runStageInPod: true
steps:
  setupCommonPipelineEnvironment:
     collectTelemetryData: false
    
  mtaBuild:
    configuration.general.runStageInPod: true
    buildTarget: 'CF'
